l_english:
 DELETE_ON_IMPORT_NAME: "Paradox Game Converters: "
 DELETE_ON_IMPORT_DESC: " To "
 EXIT: "Exit"
 ABOUT: "About"
 SUPPORT_US: "Support us on Patreon"
 MENUCONVERTER: "Converter"
 MENUPGCG: "PGCG"
 FOOTER: "Paradox Game Converters Group"
 ABOUTBODY: "Copyright (c) 2020 The Paradox Game Converters Group\n\nThis converter, as all others, is free and available at our Github repository.\n\nGithub. Forums. Wiki pages. Steam. If you need to find us, report bugs, offer suggestions or wish to participate, we're there."
 ABOUTTITLE: "Paradox Game Converters Group - Universal Frontend"
 LOGTIME: "Timestamp"
 LOGSEVERITY: "Vehemence"
 LOGMESSAGE: "Message"
 CONVERTSAVING: "Saving Configuration:"
 CONVERTCONVERTING: "Converting Save:"
 CONVERTCOPYING: "Copying Mod:"
 CONVERTSTATUSPRE: "Not Started."
 CONVERTSTATUSIN: "In Progress."
 CONVERTSTATUSPOSTSUCCESS: "Finished."
 CONVERTSTATUSPOSTFAIL: "Failed!"
 CONVERTBUTTON: "Convert Save"
 LANGUAGE: "Language"
 LANGUAGESAVED: "Language saved"
 LANGUAGESAVEDBODY: "Language has been saved, please restart frontend."
 PATHSTAB: "Paths"
 OPTIONSTAB: "Options"
 CONVERTTAB: "Convert"
 MODSTAB: "Mods"
 MODSDISABLED: "Mod autodetection disabled by configuration/not required."
 MODSNOTFOUND: "Mods not found in mod directory."
 MODSFOUND: "Mods autodetected:"
 BROWSE: "Browse"
 LOGLEVEL: "Filter Log Messages Below Severity"
 LOGLEVEL0: "Error"
 LOGLEVEL1: "Warning"
 LOGLEVEL2: "Info"
 LOGLEVEL3: "Debug"
