l_chinese:
  EDITOR_SETTINGS: "编辑器设置"
  PERFORMANCE: "效能"
  SPACE: "空格"
  SPACES: "空格"
  TAB: "制表符（TAB）"
  TABS: "制表符（TAB）"
  EXTERNAL_EDITOR: "外部编辑器"
  EXTERNAL_EDITOR_DESC: "在点击编辑按钮时将会打开外部编辑器。"
  SELECT_PROGRAM: "选择外部编辑器"
  INDENTATION: "缩进风格"
  INDENTATION_DESC: "在外部编辑器中使用的缩进风格。"
  PAGE_SIZE: "页面大小"
  PAGE_SIZE_DESC: "每页所显示的节点数量上限。\n显示的节点越多，加载时间越长。"
  MAX_TOOLTIP_LINES: "提示框行数上限"
  MAX_TOOLTIP_LINES_DESC: "节点预览提示框的行数上限。"
  ENABLE_NODE_TAGS: "启用节点标签"
  ENABLE_NODE_TAGS_DESC: "由于每个节点的节点标签都需要单独计算，因此将会影响效能。"
  ENABLE_NODE_JUMPS: "启用节点跳转"
  ENABLE_NODE_JUMPS_DESC: "由于每个节点都需要进行分析以确定跳转位置，因此将会影响效能。"
  WARN_ON_TYPE_CHANGE: "启用类型变更警告"
  WARN_ON_TYPE_CHANGE_DESC: "在一个条目的数据类型被改变时发出警告，这通常不是正常操作。"